### ISSUE TITLE
Perk Selection no longer functioning

### ISSUE THREAD

**Issue by delphiactual** [DestinyItemManager/DIM#1453]
https://www.reddit.com/r/DestinyItemManager/comments/5rb7ty/bug_in_loadout_builder_perk_locking_buttons_chrome/
```
Error: [$injector:unpr] Unknown provider: nProvider <- n
http://errors.angularjs.org/1.6.1/$injector/unpr?p0=nProvider%20%3C-%20n
    at chrome-extension://mkiipknpfaacbjdagdeppdacpgpdjklc/main-5fc9ce.js:7:21156
    at chrome-extension://mkiipknpfaacbjdagdeppdacpgpdjklc/main-5fc9ce.js:8:11018
    at Object.r [as get] (chrome-extension://mkiipknpfaacbjdagdeppdacpgpdjklc/main-5fc9ce.js:8:9920)
    at chrome-extension://mkiipknpfaacbjdagdeppdacpgpdjklc/main-5fc9ce.js:8:11103
    at r (chrome-extension://mkiipknpfaacbjdagdeppdacpgpdjklc/main-5fc9ce.js:8:9920)
    at i (chrome-extension://mkiipknpfaacbjdagdeppdacpgpdjklc/main-5fc9ce.js:8:10225)
    at Object.o [as invoke] (chrome-extension://mkiipknpfaacbjdagdeppdacpgpdjklc/main-5fc9ce.js:8:10446)
    at l.instance (chrome-extension://mkiipknpfaacbjdagdeppdacpgpdjklc/main-5fc9ce.js:9:5454)
    at chrome-extension://mkiipknpfaacbjdagdeppdacpgpdjklc/main-5fc9ce.js:39:23985
    at u (chrome-extension://mkiipknpfaacbjdagdeppdacpgpdjklc/main-5fc9ce.js:9:26311) Possibly unhandled rejection: {}
```

**Comment by davidc14** [comment]
I'm now receiving this error now after updating to 3.16.1.
```
main-e85cf9.js:34255 Error: [$injector:unpr] Unknown provider: nProvider <- n
http://errors.angularjs.org/1.6.1/$injector/unpr?p0=nProvider%20%3C-%20n
    at chrome-extension://apghicjnekejhfancbkahkhdckhdagna/main-e85cf9.js:8:30587
    at chrome-extension://apghicjnekejhfancbkahkhdckhdagna/main-e85cf9.js:9:20581
    at Object.r [as get] (chrome-extension://apghicjnekejhfancbkahkhdckhdagna/main-e85cf9.js:9:19483)
    at chrome-extension://apghicjnekejhfancbkahkhdckhdagna/main-e85cf9.js:9:20666
    at r (chrome-extension://apghicjnekejhfancbkahkhdckhdagna/main-e85cf9.js:9:19483)
    at i (chrome-extension://apghicjnekejhfancbkahkhdckhdagna/main-e85cf9.js:9:19788)
    at Object.o [as invoke] (chrome-extension://apghicjnekejhfancbkahkhdckhdagna/main-e85cf9.js:9:20009)
    at l.instance (chrome-extension://apghicjnekejhfancbkahkhdckhdagna/main-e85cf9.js:10:14999)
    at chrome-extension://apghicjnekejhfancbkahkhdckhdagna/main-e85cf9.js:43:8293
    at u (chrome-extension://apghicjnekejhfancbkahkhdckhdagna/main-e85cf9.js:11:3852) Possibly unhandled rejection: {}
(anonymous) @ main-e85cf9.js:34255
(anonymous) @ main-e85cf9.js:34255
c @ main-e85cf9.js:40222
$eval @ main-e85cf9.js:40222
$digest @ main-e85cf9.js:40222
$apply @ main-e85cf9.js:40222
(anonymous) @ main-e85cf9.js:40420
dispatch @ main-e85cf9.js:18123
g.handle @ main-e85cf9.js:15230
```

**Comment by SunburnedGoose** [comment]
Thanks for the update.

**Comment by davidc14** [comment]
Is there anything else I can do to help here?

**Comment by SunburnedGoose** [comment]
I fixed it.

We were relying on auto-detection with ngAnnotate to find dependencies.  The way forward is to be explicit with your injection statements, or do it yourself.  It will go out in a release soon.
